/**
 * cache.js
 * Read-only cache for demo day.
 *
 * Cache files are pre-generated by scripts/precache.js and committed to the repo.
 * We NEVER write at runtime (serverless filesystem is read-only on Vercel).
 * The artificial delay makes pre-cached responses feel like live AI calls.
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CACHE_DIR  = path.join(__dirname, '../data/cache');
const DELAY_MS   = parseInt(process.env.ARTIFICIAL_DELAY_MS ?? '1200', 10);

/**
 * Returns the cached response for a company/endpoint pair, or null if not found.
 * @param {string} companyId
 * @param {string} endpoint  - 'analyze' | 'predict' | 'map'
 * @returns {object|null}
 */
export function getCachedResponse(companyId, endpoint) {
  const filePath = path.join(CACHE_DIR, `${companyId}-${endpoint}.json`);
  if (!fs.existsSync(filePath)) return null;

  try {
    return JSON.parse(fs.readFileSync(filePath, 'utf8'));
  } catch {
    return null;
  }
}

/**
 * Simulates AI "thinking time" so the demo doesn't feel instant.
 * Randomises ±300ms around the configured delay so it feels human.
 */
export async function simulateThinking() {
  const jitter = Math.floor(Math.random() * 600) - 300;
  await new Promise(r => setTimeout(r, DELAY_MS + jitter));
}
